output_path: "/scratch/indikar_root/indikar1/shared_data/hybrid_library_2/"
inputs: "config/fastq_paths.txt"
hashing_read_dir: "/nfs/turbo/umms-indikar/shared/projects/hybrid_reprogramming/data/fastq/biolegend_library/2024-12-06-TSB-1N-2T-primers/fastq_pass/"
hash_sequences: "config/hashing_sequences.fasta"
ref_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz" 
transcript_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.cdna.all.fa.gz" 
gtf_path: "/nfs/turbo/umms-indikar/shared/projects/HSC/data/RefGenome/Homo_sapiens.GRCh38.107.gtf"
expected_cells: 10000
barcode_whitelist: "/nfs/turbo/umms-indikar/shared/projects/cell_cycle/data/10x_barcode_lists/3M-3pgex-may-2023.txt"
barcode_translation: "/nfs/turbo/umms-indikar/shared/projects/cell_cycle/data/10x_barcode_lists/3M-3pgex-may-2023_translation.txt"
minimap2_args: "-ax splice -uf --secondary=no --MD" 
umi_distance: 1
threads: 36
